### ISSUE TITLE
Upgrade to aiohttp 3.x.y

### ISSUE THREAD

**Issue by JohanLorenzo** [taskcluster/taskcluster-client.py#96]
From https://github.com/mozilla-releng/scriptworker/pull/184:

aiohttp 3.0.0 was [released yesterday](https://github.com/aio-libs/aiohttp/releases/tag/v3.0.0). Scriptworker has an installation problem, because taskcluster [prevents 3.0.0 from being installed](https://github.com/taskcluster/taskcluster-client.py/pull/67).

Even if we wanted taskcluster to allow 3.0.0, we would hit this [new type of failure](https://travis-ci.org/mozilla-releng/beetmoverscript/jobs/340871448#L599) on projects that depend on scriptworker.

Upgrading taskcluster would be the first step. Then, scriptworker would have to fix its test suite.

**Comment by jhford** [comment]
@escapewindow do you think you might have a chance to take a look at this?

**Comment by escapewindow** [comment]
* Per the [docs](http://aiohttp.readthedocs.io/en/stable/whats_new_3_0.html#aiohttp-whats-new-3-0), The minimal supported Python version is 3.5.3 now. We'll have to make sure that's reflected in any tests + production puppet (which I believe has 3.5.2 atm).

* We now need an `async with` for any session contexts; that's what's broken with beetmover atm.

* We continue to get strongly worded warnings for creating the session outside of a coroutine, e.g. `UserWarning: Creating a client session outside of coroutine is a very dangerous idea`. This is problematic for taskcluster-client.py because we're trying to keep the model for creating a session the same between sync and async. aiohttp's insistence on using a coroutine for the async library means we currently can't do all of the following:

    1. keep the exact same model for session creation,
    1. avoid these strongly worded warnings, and
    1. keep the session around long term

    at the same time. Right now we have the first and third but not the second. We may be able to share the same model if we rewrite [the session creation](https://github.com/taskcluster/taskcluster-client.py/blob/master/taskcluster/client.py#L75-L78) to allow for an `await` somehow. And somehow wrap the whole thing in a `with` or `async with` and yield the output.

    An alternative solution would be to have `_createSession` return `None` for async, and wrap each call in an `async with ...`, where `...` either takes the passed-in session, or creates a new one. That means we wouldn't break the model, and we'd avoid the warnings, but we wouldn't keep the session long term unless we passed one in to tc-client.py ourselves.

It looks like we get some [good stuff in aiohttp 3](http://aiohttp.readthedocs.io/en/stable/whats_new_3_0.html#aiohttp-whats-new-3-0). I can probably look at this later, but it'll take a little time to get us upgradable.

**Comment by escapewindow** [comment]
I think I know how to tackle the `async with` problem.

* in `__init__`, `self.session = session or aiohttp.ClientSession`
* in `asyncutils`, we have functions that take a `session` kwarg. This will either be a session or the `aiohttp.ClientSession` function.
    * If it's `aiohttp.ClientSession`, then `helper_function = session; async with helper_function() as my_session:` will work.
    * if it's a session object, then we might be able to define a `helper_function` that yields the session object so we can also call it in the same way: `async with helper_function() as my_session:`

**Comment by jhford** [comment]
@escapewindow If having a different session creation model for Async would significantly improve how it is to use, I think it might be worth while.  I think having the session creation be identical between sync/async would be ideal, but if that forces us to use a really weird way of doing things, I think that's justification to do it differently between them.

Is it possible to have it so that when not using a specific agent, that the calling convention be the same (minus the async loop setup), but have differing async vs sync process for setting up the session?

If we change how sessions are created, we should bump to version 4.0.0 at the same time.

**Comment by escapewindow** [comment]
To answer @catlee 's q:

```
#!/usr/bin/env python

import aiohttp
import asyncio
from taskcluster.async import Queue
import logging

logging.basicConfig()
log = logging.getLogger()
log.setLevel(logging.DEBUG)

async def foo(session=None):
    queue = Queue()
    async with aiohttp.ClientSession() as session:
        async with Queue(session=session) as queue:
            print(await queue.listProvisioners())
        # make sure session isn't closed if we nest contextmanagers
        r = await session.get("https://google.com")
        print(await r.text())


loop = asyncio.get_event_loop()
loop.run_until_complete(foo())
```

works.
